packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20
  "@types/eslint": ^8
  "convex": ^1.17.4
  "@convex-dev/auth": ^0.0.80
  "convex-helpers": ^0.1.67

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": 19.0.4
    "@types/react-dom": 19.0.2
