name: "Bug Report"
description: "Report a bug in the project"
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## Describe the bug"
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue here..."
    validations:
      required: true
milestone: Phase one

project: "project"
assignees:
  - "saranatour1"