name: Add bugs to bugs project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub projects
        uses: actions/add-to-project@v1.0.2
        with:
          # Replace with your actual project URL
          project-url: https://github.com/users/saranatour1/projects/8
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          labeled: bug, needs-triage
          label-operator: OR
